// Generated by CoffeeScript 1.3.3
(function() {
  var createTextField, f, fields, scrollView, submit, win, _i, _len;

  createTextField = function(hint, value) {
    if (value == null) {
      value = '';
    }
    return Ti.UI.createTextField({
      hintText: hint,
      id: hint,
      value: value,
      width: Ti.UI.FILL,
      height: Ti.UI.SIZE
    });
  };

  win = Ti.UI.createWindow({
    title: 'Appygram Test'
  });

  win.add(scrollView = Ti.UI.createScrollView({
    height: Ti.UI.FILL,
    width: Ti.UI.FILL
  }));

  fields = ['name', 'email', 'message', 'api_key'];

  for (_i = 0, _len = fields.length; _i < _len; _i++) {
    f = fields[_i];
    scrollView.add(createTextField(f, (f === 'api_key' ? 'blah' : '')));
  }

  scrollView.add(submit = Ti.UI.createButton({
    title: 'Submit to appygram',
    width: Ti.UI.FILL,
    height: Ti.UI.SIZE
  }));

  submit.addEventListener('click', function() {
    var child, params, _j, _len1, _ref;
    params = {};
    _ref = scrollView.getChildren();
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      child = _ref[_j];
      if (child.id != null) {
        params[child.id] = child.value;
      }
    }
    return appygram.submitFeedback(params, function(e) {
      if (e) {
        return alert(e);
      } else {
        return alert('Thanks for the feedback!!');
      }
    });
  });

  win.open();

}).call(this);
