// Generated by CoffeeScript 1.3.3
(function() {
  var endpoint;

  endpoint = 'http://api.appygram.com';

  exports.sendFeedback = function(params, cb, error) {
    var client;
    client = Ti.Network.createHTTPClient({
      onload: function(e) {
        return cb(null, this.responseText);
      },
      onerror: function(e) {
        return cb(e.error);
      }
    });
    client.open('POST', endpoint + '/appygrams');
    client.setRequestHeader("Accept", "application/json");
    return client.send(params);
  };

  exports.getFeedbackTypes = function(api_key, cb) {
    var client;
    client = Ti.Network.createHTTPClient({
      onload: function(e) {
        return cb(null, JSON.parse(this.responseText));
      },
      onerror: function(e) {
        return cb(e.error);
      }
    });
    client.open('GET', endpoint + '/api/distrobutions/' + api_key);
    return client.send();
  };

}).call(this);
