// Generated by CoffeeScript 1.4.0
(function() {
  var AppygramController, appygram, default_settings;

  appygram = require('./appygram');

  default_settings = require('./default_settings');

  AppygramController = (function() {

    function AppygramController(api_key, default_settings) {
      this.api_key = api_key;
      this.default_settings = default_settings != null ? default_settings : default_settings;
    }

    AppygramController.prototype.getFeedbackTypesTable = function(cb) {
      var _this = this;
      return appygram.getFeedbackTypes(this.api_key, function(error, types) {
        var data, key, value;
        if (error) {
          return cb(error);
        }
        data = [];
        for (key in types) {
          value = types[key];
          data.push({
            title: value
          });
        }
        return cb(null, Ti.UI.createTableView({
          data: data
        }));
      });
    };

    return AppygramController;

  })();

  exports.controller = AppygramController;

  exports.sdk = appygram;

}).call(this);
