spawn = require('child_process').spawn
pipe = (p)->
  p.stdout.on 'data', (d)->
    console.log d.toString()
  p.stderr.on 'data', (d)->
    console.log d.toString()
task 'dev', 'compile coffee and put into correct dirs', ->
  s = spawn 'coffee', ['-o', 'Resources/',  '-cw', 'src/']
  pipe s

task 'andy_dev', 'build and install to device', ->
  console.log('Please define ANDROID_SDK in your environment') unless process.env.ANDROID_SDK?
  process.exit() unless process.env.ANDROID_SDK?
  andy = spawn 'tsm', ['builder', '3.0.0', 'android', 'install', 'testproject', process.env.ANDROID_SDK, __dirname, 'com.wlaurance.testproject', 5]
  pipe andy

task 'emulator', 'run on an emulator', ->
  console.log('Please define ANDROID_SDK in your environment') unless process.env.ANDROID_SDK?
  process.exit() unless process.env.ANDROID_SDK?
  andy = spawn 'tsm', ['run', '3.0.0', 'run', '--platform=android']
  pipe andy
  andy.on 'close', ->
    process.exit()
